"""create prices table

Revision ID: a296414ef43b
Revises: 13267b461cd7
Create Date: 2026-01-17 15:08:03.370486

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a296414ef43b'
down_revision: Union[str, Sequence[str], None] = '13267b461cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(length=10), nullable=False),
                    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
                    sa.Column('timestamp', sa.BigInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='public'
                    )
    op.create_index(op.f('ix_public_prices_ticker'), 'prices', ['ticker'], unique=False, schema='public')
    op.create_index(op.f('ix_public_prices_timestamp'), 'prices', ['timestamp'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_prices_timestamp'), table_name='prices', schema='public')
    op.drop_index(op.f('ix_public_prices_ticker'), table_name='prices', schema='public')
    op.drop_table('prices', schema='public')
    # ### end Alembic commands ###
